### ISSUE TITLE
[!] Unable to find a specification for `ABGaugeViewKit`

### ISSUE THREAD

**Issue by rajan2211** [AjayBhanushali/ABGaugeViewKit#1]
I am not able to install the library using Cocoapods

**Comment by gopinath0332** [comment]
I am also hitting the same problem. Unable to install through coco pod

**Comment by AjayBhanushali** [comment]
Hi @rajan2211 and @gopinath0332 , 

Can you elaborate more about the process you are following as I am able to install it using cocoapods.
Please [click here](https://medium.com/ajay-bhanushali/create-gaugeview-speedometer-in-swift-571ff97d1a68) for the tutorial guide.

**Comment by AjayBhanushali** [comment]
no response yet. Hence, closing.

**Comment by mahdigh99** [comment]
I've the same problem @AjayBhanushali 

<img width="1218" alt="Screen Shot 1398-01-12 at 11 40 58" src="https://user-images.githubusercontent.com/24169864/55309510-452c1580-5473-11e9-87c5-e851e08c00fc.png">

I'm going step by step -> [medium](https://medium.com/ajay-bhanushali/create-gaugeview-speedometer-in-swift-571ff97d1a68)
